name: mesas-GMD
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - meson>0.55.0
  - ninja>=1.8.2
  - numpy>=1.22
  - scipy>=1.3.1
  - pandas>=1.1.0
  - pytest>=6.0.1
  - matplotlib>=3.3.0
  - ipykernel
