name: mesas-GMD
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - matplotlib[version='>=3.3.0']
  - meson=1.3.2
  - numpy[version='>=1.22']
  - pandas[version='>=1.1.0']
  - pytest[version='>=6.0.1']
  - scikit-learn[version='>=0.23.2']
  - scipy[version='>=1.3.1']
  - gfortran
