name: Python 🐍 CI/CD tests

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.bib"
      - "**/*.ya?ml"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - "**/*.md"
      - "**/*.bib"
      - "**/*.ya?ml"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

jobs:
  build:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          activate-environment: mesas-GMD
          environment-file: environment.yml
          use-mamba: true  # Optional: Speeds up installation

      - name: Install project dependencies
        run: pip install .

      - name: Run unit tests
        run: pytest test
